site_name: tinyDocs
site_url: https://docs.mr.industries/
repo_url: https://github.com/Mister-Industries/tinyCore
repo_name: Mister-Industries/tinyCore
theme:  
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/tinyLogoWhite.png'
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: blue
      accent: purple
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - content.footnote.tooltips
    - content.code.copy
    - content.code.line_numbers

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

watch:
    - overrides

plugins:
    - search
    - blog: 
        authors_profiles: true
        authors_profiles_name: Authors
        archive: true
        archive_date_format: yyyy
        archive_name: Archive
        archive_pagination: true
        categories: true
        blog_dir: 7_blog
    #- live-edit
    

nav:
  - Home: index.md
  
  - Get Started: 
    - 1_get-started/index.md
    - Unboxing: 1_get-started/unboxing.md
    - Setup Arduino IDE: 1_get-started/arduino-ide.md
    - Setup the IMU: 1_get-started/imu.md
    - Build your First Project: 1_get-started/motion-tracker.md
    - Explore More!: docs-explorer/index.md
  
  #- tinyCore: 
    
  - Basics:
    - Blink an LED: 2_tiny-core/basics/blink-led.md
    - Buzz a Buzzer: 2_tiny-core/basics/buzz-buzzer.md
    - Read a Button Press: 2_tiny-core/basics/button-press.md
    - Read Analog Sensor Values: 2_tiny-core/basics/read-sensor-value.md
    - Detect Motion with the IMU: 2_tiny-core/basics/detect-motion.md
    - Save Data to the SD Card: 2_tiny-core/basics/save-data-to-sdcard.md
    - Connect a Display via I2C: 2_tiny-core/basics/i2c-display.md
    - Use the Serial Monitor & Plotter: 2_tiny-core/basics/serial-monitor-plotter.md
    - Connect to WiFi: 2_tiny-core/basics/wifi.md
    - Connect to Bluetooth: 2_tiny-core/basics/bluetooth.md
    - Link two tinyCores: 2_tiny-core/basics/link-tiny-cores.md

  - Advanced:
    - Save Data to Google Sheets: 2_tiny-core/advanced/google-sheets.md
    - Save Data to Thingspeak: 2_tiny-core/advanced/thingspeak.md
    - Host a Website Interface: 2_tiny-core/advanced/website-interface.md
    - Dabble App (Bluetooth):
      - Setup the Dabble App: 2_tiny-core/advanced/dabble-app.md
      - Blink an LED: 2_tiny-core/advanced/dabble-app-led.md
      - Use a Controller: 2_tiny-core/advanced/dabble-app-controller.md
      #- Move a Servo Motor: 2_tiny-core/advanced/dabble-app-servo.md

      #BACKLOG
      #- Run AI Models (tinyML): 2_tiny-core/advanced/tinyML.md
      #- Pretend to be a Keyboard: 2_tiny-core/advanced/keyboard.md
      #- Make a MIDI Instrument: 2_tiny-core/advanced/midi-instrument.md
      #- Use USB Mass Storage: 2_tiny-core/advanced/usb-mass-storage.md
      #- Use Smart Home: 2_tiny-core/advanced/esp-smart-home.md

  #- tinyHATs:
    #- 3_tiny-hats/index.md
    #- tinyGlow: 3_tiny-hats/tinyGlow.md
    #- tinyVoice: 3_tiny-hats/tinyVoice.md
    #- tinyDisplay: 3_tiny-hats/tinyDisplay.md
    #- tinySniff: 3_tiny-hats/tinySniff.md
    #- tinyProto: 3_tiny-hats/tinyProto.md
    #- tinyMove: 3_tiny-hats/tinyMove.md

  - Reference:
    - 5_reference/index.md
    
    - Basics:
      - What is GPIO?: 5_reference/basics/gpio.md
      - What is I2C?: 5_reference/basics/i2c.md
      - What is an IMU?: 5_reference/basics/imu.md
      - What is Serial Communication?: 5_reference/basics/serial-communication.md
      - What is an SD Card?: 5_reference/basics/sd-card.md
      - What is ESP-NOW?: 5_reference/basics/esp-now.md

    - Advanced:
      - What is I2S?: 5_reference/advanced/i2s.md
      - What is an ADC?: 5_reference/advanced/adc.md
      - What is a DAC?: 5_reference/advanced/dac.md
      - What is DMA/FastADC?: 5_reference/advanced/dma-fastadc.md
      - What is WiFi?: 5_reference/advanced/wifi.md
      - What is Bluetooth?: 5_reference/advanced/bluetooth.md
      - What is PWM?: 5_reference/advanced/pwm.md
      #- What is HID?: 5_reference/advanced/hid.md
      #- What is MIDI?: 5_reference/advanced/midi.md
      #- What is tinyML?: 5_reference/advanced/tinyml.md

    - FAQ: 5_reference/FAQ.md

  - User Projects: 
    - 6_user-projects/index.md
    - Motion Tracker: 6_user-projects/motion-tracker.md    

  - Blog: 7_blog/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@FacioErgoSum
    - icon: simple/bluesky
      link: https://bsky.app/profile/mr.industries
    - icon: simple/notion
      link: https://emphasized-crop-755.notion.site/
    - icon: material/linkedin
      link: https://www.linkedin.com/company/mister-industries
  analytics:
    provider: google
    property: G-93QSYCNXQS
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2025 MR.INDUSTRIES LLC –
  <a href="#__consent">Change cookie settings</a>