authors:
  macgeoffrey:
    name: Geoff McIntyre
    description: Co-founder - CEO
    avatar: https://avatars.githubusercontent.com/u/21022845
    url: https://github.com/FacioErgoSum
  alexvoss:
    name: Aiden Reeves
    description: Co-founder - COO
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
  katharinalisalin:
    name: Kathi
    description: Communications
    avatar: https://avatars.githubusercontent.com/u/105352741
    url: https://github.com/katharinalisalin
